before_install:
 - chmod +x gradlew

language: android
sudo: false
android:
  components:
    - tools
    - build-tools-25.0.2
    - platform-tools
    - extra-android-m2repository
    - extra-google-android-support
    - android-25

jdk: oraclejdk8
os:
  - linux

script: ./gradlew build check
